/*
 * This file is generated by jOOQ.
 */
package db.com.example.demo.db.tables.daos;


import com.example.demo.db.tables.Person;

import java.util.List;

import javax.annotation.processing.Generated;

import db.com.example.demo.db.tables.records.PersonRecord;
import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class PersonDao extends DAOImpl<PersonRecord, com.example.demo.db.tables.pojos.Person, Integer> {

    /**
     * Create a new PersonDao without any configuration
     */
    public PersonDao() {
        super(Person.PERSON_, com.example.demo.db.tables.pojos.Person.class);
    }

    /**
     * Create a new PersonDao with an attached configuration
     */
    @Autowired
    public PersonDao(Configuration configuration) {
        super(Person.PERSON_, com.example.demo.db.tables.pojos.Person.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer getId(com.example.demo.db.tables.pojos.Person object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>ID IN (values)</code>
     */
    public List<com.example.demo.db.tables.pojos.Person> fetchById(Integer... values) {
        return fetch(Person.PERSON_.ID, values);
    }

    /**
     * Fetch a unique record that has <code>ID = value</code>
     */
    public com.example.demo.db.tables.pojos.Person fetchOneById(Integer value) {
        return fetchOne(Person.PERSON_.ID, value);
    }

    /**
     * Fetch records that have <code>NAME IN (values)</code>
     */
    public List<com.example.demo.db.tables.pojos.Person> fetchByName(String... values) {
        return fetch(Person.PERSON_.NAME, values);
    }

    /**
     * Fetch records that have <code>EMAIL IN (values)</code>
     */
    public List<com.example.demo.db.tables.pojos.Person> fetchByEmail(String... values) {
        return fetch(Person.PERSON_.EMAIL, values);
    }
}
