/*
 * This file is generated by jOOQ.
 */
package com.example.demo.db;


import com.example.demo.db.tables.Person;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in person
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>person.PERSON</code>.
     */
    public static final Person PERSON_ = com.example.demo.db.tables.Person.PERSON_;
}
